# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject'),
        ),
    ]
