# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20160825_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='', upload_to='path/', verbose_name='Label'),
            preserve_default=False,
        ),
    ]
