# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(upload_to='path/', verbose_name='Subject Icon'),
        ),
    ]
