# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20160826_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
