# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hr_id', models.CharField(max_length=2)),
                ('grade_level', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default='1993-09-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='F', max_length=2),
            preserve_default=False,
        ),
    ]
