# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_testscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=60)),
                ('score', models.CharField(max_length=5)),
                ('percentile', models.CharField(max_length=3, null=True)),
                ('test_session', models.CharField(max_length=60, null=True)),
                ('subject', models.CharField(max_length=60, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='testscores',
            name='student',
        ),
        migrations.DeleteModel(
            name='TestScores',
        ),
    ]
