# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20161107_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='quarter_grade',
            field=models.IntegerField(null=True),
        ),
    ]
