# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_load_hs_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschool',
            old_name='admit_points',
            new_name='tier1_points',
        ),
        migrations.RemoveField(
            model_name='highschool',
            name='school_name',
        ),
        migrations.AddField(
            model_name='highschool',
            name='full_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='tier2_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='tier3_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='tier4_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='tier5_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
