# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20161202_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highschool',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
