# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20161202_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='full_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='logo',
            field=models.ImageField(upload_to='images/hs_icons', verbose_name='HS Logo'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='tier1_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='tier2_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='tier3_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='tier4_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
