# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('assign_name', models.CharField(max_length=300)),
                ('assign_score', models.IntegerField()),
                ('assign_score_possible', models.IntegerField()),
                ('category_name', models.CharField(max_length=300)),
                ('assignment_due', models.DateField()),
                ('grade_entered', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='description',
        ),
        migrations.AddField(
            model_name='email',
            name='user_type',
            field=models.CharField(default='Student', max_length=100),
            preserve_default=False,
        ),
    ]
