# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20170126_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
