# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20170126_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
