# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20170131_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_score_possible',
            field=models.FloatField(),
        ),
    ]
