# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20170307_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_score',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_score_possible',
            field=models.CharField(max_length=4),
        ),
    ]
