# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20170307_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category_weight',
            field=models.CharField(default=10, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='student_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roster',
            name='student_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
