# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20170412_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_student',
            field=models.BooleanField(default=True),
        ),
    ]
