# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_student_current_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_student',
        ),
        migrations.AddField(
            model_name='roster',
            name='current_student',
            field=models.BooleanField(default=True),
        ),
    ]
