# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_testscore_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='test_date',
            field=models.DateField(null=True),
        ),
    ]
