# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20170426_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='STMathRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcd', models.CharField(max_length=150)),
                ('num_lab_logins', models.IntegerField()),
                ('k_5_progress', models.DecimalField(decimal_places=1, max_digits=4)),
                ('k_5_mastery', models.DecimalField(decimal_places=1, max_digits=4)),
                ('curr_hurdle', models.IntegerField()),
                ('cur_objective', models.CharField(max_length=150)),
                ('total_time', models.IntegerField()),
                ('metric_date', models.DateField(null=True)),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
