# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_stmathrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stmathrecord',
            old_name='cur_objective',
            new_name='curr_objective',
        ),
    ]
