# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20170516_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='NWEAPercentileConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('season', models.CharField(max_length=150)),
                ('grade_level', models.CharField(max_length=2)),
                ('percentile', models.IntegerField()),
                ('rit', models.IntegerField()),
            ],
        ),
    ]
