# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20170601_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nweapercentileconversion',
            name='grade_level',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nweapercentileconversion',
            name='percentile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nweapercentileconversion',
            name='rit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweapercentileconversion',
            name='season',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nweapercentileconversion',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
