# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_auto_20170613_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subjectinfo',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='subjectinfo',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
