# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_auto_20170623_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/subj_icons', verbose_name='Subject Icon'),
        ),
    ]
