# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_auto_20170623_2024'),
        ('student', '0045_auto_20170623_2059'),
    ]

    operations = [
    ]
